# Generated by Django 5.2.11 on 2026-04-22 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_profileimage_user_profile_image_enum'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialaccount',
            name='refresh_token',
            field=models.TextField(blank=True, default=''),
        ),
    ]
