# Generated by Django 5.2.11 on 2026-04-02 06:23

import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='preset_homes/')),
            ],
            options={
                'db_table': 'home_images',
            },
        ),
        migrations.CreateModel(
            name='StarterPack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'starter_packs',
            },
        ),
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('invite_code', models.CharField(max_length=6, unique=True)),
                ('creation_step', models.IntegerField(choices=[(1, '집 프로필'), (2, '집안일'), (3, '리워드')], default=1)),
                ('status', models.CharField(choices=[('draft', '생성 중'), ('active', '활성')], default='draft', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='homes', to='homes.homeimage')),
            ],
            options={
                'db_table': 'homes',
            },
        ),
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('goal_point', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rewards', to='homes.home')),
            ],
            options={
                'db_table': 'rewards',
            },
        ),
        migrations.CreateModel(
            name='Chore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='chores/')),
                ('repeat_days', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(choices=[(0, '월'), (1, '화'), (2, '수'), (3, '목'), (4, '금'), (5, '토'), (6, '일')]), default=list, size=None)),
                ('difficulty', models.IntegerField(choices=[(1, '하'), (2, '중하'), (3, '중'), (4, '중상'), (5, '상')])),
                ('starter_pack', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chores', to='homes.starterpack')),
            ],
            options={
                'db_table': 'chores',
            },
        ),
        migrations.CreateModel(
            name='HomeChore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chore', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_chores', to='homes.chore')),
                ('home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_chores', to='homes.home')),
            ],
            options={
                'db_table': 'home_chores',
                'unique_together': {('home', 'chore')},
            },
        ),
        migrations.CreateModel(
            name='HomeMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.IntegerField(choices=[(1, '관리자'), (2, '구성원')])),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='homes.home')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'home_members',
                'unique_together': {('home', 'user')},
            },
        ),
    ]
