# Generated by Django 5.2.11 on 2026-04-17 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homes', '0002_remove_homeimage_home_image_enum_chore_image_enum'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='home',
            name='creation_step',
        ),
        migrations.AlterField(
            model_name='home',
            name='status',
            field=models.CharField(choices=[('draft', '생성 중'), ('active', '활성')], default='active', max_length=10),
        ),
    ]
