# Generated by Django 5.2.11 on 2026-04-17 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homes', '0003_remove_home_creation_step'),
    ]

    operations = [
        migrations.AddField(
            model_name='chore',
            name='points',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='chore',
            name='difficulty',
            field=models.IntegerField(choices=[(1, '쉬움'), (2, '중간'), (3, '어려움')]),
        ),
    ]
