# Generated by Django 5.2.11 on 2026-04-17 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homes', '0004_chore_points_difficulty_3level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chore',
            name='image',
        ),
        migrations.RemoveField(
            model_name='chore',
            name='points',
        ),
        migrations.AddField(
            model_name='chore',
            name='category',
            field=models.IntegerField(choices=[(1, '쓰레기'), (2, '욕실'), (3, '주방'), (4, '거실'), (5, '침실'), (6, '빨래'), (7, '요리'), (8, '설거지'), (9, '청소기'), (10, '기타')]),
        ),
        migrations.AddField(
            model_name='chore',
            name='description',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='chore',
            name='difficulty',
            field=models.IntegerField(choices=[(1, '하'), (2, '중하'), (3, '중'), (4, '중상'), (5, '상')]),
        ),
        migrations.AlterField(
            model_name='chore',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
