# Generated by Django 5.2.11 on 2026-04-22 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homes', '0005_chore_category_description_difficulty_5level'),
    ]

    operations = [
        migrations.AddField(
            model_name='homechore',
            name='memo',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='chore',
            name='category',
            field=models.IntegerField(choices=[(1, '쓰레기'), (2, '욕실'), (3, '청소'), (4, '주방'), (5, '세탁')]),
        ),
        migrations.AlterField(
            model_name='chore',
            name='description',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
