# Generated by Django 6.0.5 on 2026-05-12 15:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homes', '0006_chore_category_5_description_20_homechore_memo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homechore',
            name='memo',
        ),
        migrations.CreateModel(
            name='HomeChoreNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_chore_notes', to=settings.AUTH_USER_MODEL)),
                ('home_chore', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='homes.homechore')),
            ],
            options={
                'db_table': 'home_chore_notes',
                'ordering': ['id'],
            },
        ),
    ]
