# Generated by Django 6.0.2 on 2026-05-17 13:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homes', '0007_remove_homechore_memo_homechorenote'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChoreCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chore_completions', to=settings.AUTH_USER_MODEL)),
                ('home_chore', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completions', to='homes.homechore')),
            ],
            options={
                'db_table': 'chore_completions',
                'indexes': [models.Index(fields=['home_chore', 'date'], name='chore_compl_home_ch_c265d3_idx')],
                'unique_together': {('home_chore', 'date')},
            },
        ),
    ]
