# Generated by Django 6.0.2 on 2026-07-04 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homes', '0008_chorecompletion'),
    ]

    operations = [
        migrations.AddField(
            model_name='homechore',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
