# Generated by Django 6.0.2 on 2026-07-04 07:28

import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homes', '0009_homechore_is_active'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField()),
                ('status', models.CharField(choices=[('proposed', '제안됨'), ('confirmed', '확정됨'), ('expired', '만료됨')], default='proposed', max_length=10)),
                ('generated_at', models.DateTimeField()),
                ('member_uids_snapshot', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=36), default=list)),
                ('chore_fingerprint', models.CharField(max_length=64)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_assignments', to=settings.AUTH_USER_MODEL)),
                ('home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_assignments', to='homes.home')),
            ],
            options={
                'db_table': 'weekly_assignments',
            },
        ),
        migrations.CreateModel(
            name='AssignmentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.IntegerField(choices=[(0, '월'), (1, '화'), (2, '수'), (3, '목'), (4, '금'), (5, '토'), (6, '일')])),
                ('chore_name', models.CharField(max_length=20)),
                ('category', models.IntegerField(choices=[(1, '쓰레기'), (2, '욕실'), (3, '청소'), (4, '주방'), (5, '세탁')])),
                ('difficulty', models.IntegerField(choices=[(1, '하'), (2, '중하'), (3, '중'), (4, '중상'), (5, '상')])),
                ('point', models.IntegerField()),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignment_items', to=settings.AUTH_USER_MODEL)),
                ('home_chore', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignment_items', to='homes.homechore')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='homes.weeklyassignment')),
            ],
            options={
                'db_table': 'assignment_items',
                'ordering': ['weekday', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='weeklyassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'proposed')), fields=('home', 'week_start'), name='uniq_proposed_assignment_per_home_week'),
        ),
        migrations.AddConstraint(
            model_name='weeklyassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'confirmed')), fields=('home', 'week_start'), name='uniq_confirmed_assignment_per_home_week'),
        ),
    ]
