# Generated by Django 6.0.2 on 2026-08-03 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homes', '0011_move_reward_to_rewards'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentitem',
            name='change_type',
            field=models.CharField(blank=True, choices=[('new', '추가됨'), ('updated', '수정됨')], max_length=10, null=True),
        ),
    ]
