# Generated by Django 6.0.2 on 2026-07-23 14:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("homes", "0011_move_reward_to_rewards"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WeeklyReport",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("week_start", models.DateField()),
                ("total_count", models.PositiveIntegerField(default=0)),
                ("completed_count", models.PositiveIntegerField(default=0)),
                ("progress_rate", models.PositiveIntegerField(default=0)),
                ("mvp_name", models.CharField(blank=True, default="", max_length=8)),
                ("mvp_point", models.PositiveIntegerField(default=0)),
                ("mvp_completed_count", models.PositiveIntegerField(default=0)),
                ("member_stats", models.JSONField(default=list)),
                ("most_done", models.JSONField(blank=True, null=True)),
                ("most_missed", models.JSONField(blank=True, null=True)),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "home",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="weekly_reports", to="homes.home"
                    ),
                ),
                (
                    "mvp_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="mvp_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "weekly_reports",
                "ordering": ["-week_start"],
                "constraints": [
                    models.UniqueConstraint(fields=("home", "week_start"), name="uniq_weekly_report_per_home_week")
                ],
            },
        ),
    ]
