# Generated by Django 6.0.2 on 2026-07-23 14:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("homes", "0011_move_reward_to_rewards"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationSetting",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("push_enabled", models.BooleanField(default=True)),
                ("home_member", models.BooleanField(default=True)),
                ("assignment", models.BooleanField(default=True)),
                ("board", models.BooleanField(default=True)),
                ("reward", models.BooleanField(default=True)),
                ("report", models.BooleanField(default=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_setting",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "notification_settings",
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("home_member", "집·구성원"),
                            ("assignment", "분담안"),
                            ("board", "보드 조율"),
                            ("reward", "리워드"),
                            ("report", "리포트"),
                        ],
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("body", models.CharField(blank=True, default="", max_length=200)),
                ("deep_link", models.CharField(blank=True, default="", max_length=200)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "home",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="notifications", to="homes.home"
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "notifications",
                "ordering": ["-created_at", "-id"],
                "indexes": [models.Index(fields=["recipient", "created_at"], name="notificatio_recipie_2c3905_idx")],
            },
        ),
    ]
